src/base/urls.py
from django.urls import path

from . import views

app_name = 'base'

urlpatterns = [
    path('',views.inbox_view,name='inbox'),
    path('<int:pk>/',views.messages_view,name='messages'),
]

src/social/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from base.views import notification_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notifications/',notification_view,name='notifications'),
    path('',include('core.urls')),
    path('messages/',include('base.urls')),
    path('profile/',include('management.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/base/models.py
from django.db import models
from django.contrib.auth.models import User
    
class Message(models.Model):
    sender = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_sender')
    receiver = models.ForeignKey(User,on_delete=models.CASCADE,related_name='receiver_user')
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:10]
    
class Notification(models.Model):
    NOTIFICATION_TYPE = ((1,'Likes'),(2,'Follow'),(3,'Message'))
    user = models.ForeignKey(User,on_delete=models.DO_NOTHING)
    sender = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,related_name='sender')
    content = models.CharField(max_length=100)
    notification_type = models.IntegerField(choices=NOTIFICATION_TYPE)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.content

src/core/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify,Truncator

class Post(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='pics',blank=True)
    likes = models.ManyToManyField(User,blank=True,related_name='liked')
    slug = models.SlugField(blank=True,null=True)
    favourite = models.ManyToManyField(User,blank=True,related_name='bookmark')
    timestamp = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    
    def save(self,*args,**kwargs):
        if not self.slug:
            i = Truncator(self.name).words(45)
            self.slug = slugify(i)
        super().save(*args,**kwargs)

    def truncated_name(self):
        truncator = Truncator(self.name).chars(50)
        return truncator
    
    def number_of_likes(self):
        return self.likes.count()
    
class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    body = models.CharField(max_length=100,blank=True,null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body
    

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(blank=True,null=True,default='default-user.png',upload_to='profile')
    bio = models.TextField(blank=True,null=True)
    following = models.ManyToManyField("self",blank=True,related_name='followed_by',symmetrical=False)
    active = models.BooleanField(default=True)
    messagers = models.ManyToManyField("self",blank=True)

    def __str__(self):
        return self.user.username
    
class PasswordReset(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    reset = models.UUIDField(default=uuid.uuid4(),editable=False,unique=True)
    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

src/base/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from core.models import Profile,Post
from .models import Message,Notification

User = get_user_model()

@login_required
def notification_view(request):
    notifications = Notification.objects.filter(user=request.user,is_read=False).order_by('-timestamp')[:7]
    post = Post.objects.filter(user=request.user)
    profile = Profile.objects.exclude(user__id__in=[request.user.profile.following.values_list('id',flat=True)]).exclude(id=request.user.id).order_by('?')[:10]
    context = {'notifications':notifications,'post':post,'profile':profile}
    return render(request,'notification.html',context)

@login_required
def messages_view(request,pk):
    user = User.objects.get(id=pk)
    profile = Profile.objects.get(user=request.user)
    message = Message.objects.filter(Q(sender=request.user) & Q(receiver=user)| Q(sender=user) & Q(receiver=request.user)).order_by('timestamp')
    if request.method == 'POST':
        Message.objects.create(
            sender=request.user,
            receiver=user,
            text=request.POST.get('body')
        )
        profile.messagers.add(user.id)
        user.profile.messagers.add(request.user.id)
        Notification.objects.create(
                user=user,
                sender=request.user,
                content=f'sent a message .....',
                notification_type=3,
            )
        return redirect('base:messages',user.pk)
    context = {'message':message,'message_user':user}
    return render(request,'messages.html',context)

@login_required
def inbox_view(request):
    message = Message.objects.filter(receiver=request.user).order_by('-timestamp')
    context = {'message':message}
    return render(request,'inbox.html',context)

src/templates/comments.html
<div id="message">
    <div class="message_container">
        <div class="message">
            <div class="options">
                <div class="cart">
                    <div>
                        <div class="img">
                            <img src="{{post.image.url}}" alt="">
                        </div>
                        <div class="info">
                            <p class="name">{{post.user.get_full_name}}</p>
                        </div>
                    </div>
                </div>
                <div class="other"><a href="/" style="text-decoration: transparent; color: #000;">Home</a></div>
                <div class="other">
                    <a href="{% url 'comment' post.slug %}" style="text-decoration: transparent; color: black;">Refresh</a>
                </div>
            </div>
            <div class="content">
                {% for comment in comments %}
                <!-- <div class="my_message">
                    <p class="p_message">hello how are you?</p>
                </div>
                <div class="response_message">
                    <p class="p_message">hi! i'm fine and you?</p>
                </div> -->
                {% if comment.user == request.user %}
                <div class="my_message">
                    <p class="p_message">{{comment}}</p>&nbsp;
                </div>
                {% else %}
                <div class="response_message">
                    <p class="p_message">{{comment.user.get_full_name|lower}} ~ {{comment}}</p>
                </div>
                {% endif %}
            {% endfor %}
            </div>
            <form method="POST">
                {% csrf_token %}
                <input type="text" id="emoji" name="body" placeholder="write your comments here ...." />
            </form>

        </div>
    </div>
</div>

src/templates/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagram</title> 
    <link rel="shortcut icon" href="{% static 'assets/favicon.svg' %}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'sass/vender/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'sass/vender/bootstrap.min.css' %}">
    
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="{% static 'sass/main.css' %}">
</head>
<body>
    <div><br><br><hr>
        <center>
        <form method='POST' enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button type="submit" style="color: white ;background-color: black; border-color: transparent;">Post</button>
        </form>
        </center>
        {{request.method}}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
       
   
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script> -->
</body>
</html>

src/templates/explore.html
<div class="explore_container">
            
    <div class="items_4">
<div class="item">
  <img class="img-fluid" src="https://i.ibb.co/Jqh3rHv/img1.jpg">
  <div class="bg" <div="">
      <div class="likes">
          <img src="./images/heart_white.png">
          <span>1500</span>
      </div>
      <div class="comments">
          <img src="./images/message.png">
          <span>400</span>
      </div>
    </div>
  </div>

<div class="item">
  <img class="img-fluid" src="https://i.ibb.co/2ZxBFVp/img2.jpg">
  <div class="bg" <div="">
      <div class="likes">
          <img src="./images/heart_white.png">
          <span>400</span>
      </div>
      <div class="comments">
          <img src="./images/message.png">
          <span>200</span>
      </div>
    </div>
  </div>

<div class="item">
  <img class="img-fluid" src="https://i.ibb.co/5vQt677/img3.jpg">
  <div class="bg" <div="">
      <div class="likes">
          <img src="./images/heart_white.png">
          <span>700</span>
      </div>
      <div class="comments">
          <img src="./images/message.png">
          <span>20</span>
      </div>
    </div>
  </div>

<div class="item">
  <img class="img-fluid" src="https://i.ibb.co/FVVxR6x/img.jpg">
  <div class="bg" <div="">
      <div class="likes">
          <img src="./images/heart_white.png">
          <span>150</span>
      </div>
      <div class="comments">
          <img src="./images/message.png">
          <span>80</span>
      </div>
    </div>
  </div>


</div><div class="item1">
<div class="item">
<img class="img-fluid" src="https://i.ibb.co/CWbynB2/account3-1.jpg">
<div class="bg" <div="">
  <div class="likes">
      <img src="./images/heart_white.png">
      <span>10</span>
  </div>
  <div class="comments">
      <img src="./images/message.png">
      <span>5</span>
  </div>
</div>
</div>

</div><div class="items_4">
<div class="item">
  <img class="img-fluid" src="https://i.ibb.co/z41bG1y/img6.jpg">
  <div class="bg" <div="">
      <div class="likes">
          <img src="./images/heart_white.png">
          <span>100</span>
      </div>
      <div class="comments">
          <img src="./images/message.png">
          <span>57</span>
      </div>
    </div>
  </div>

<div class="item">
  <img class="img-fluid" src="https://i.ibb.co/vkXPdxN/account7.jpg">
  <div class="bg" <div="">
      <div class="likes">
          <img src="./images/heart_white.png">
          <span>100</span>
      </div>
      <div class="comments">
          <img src="./images/message.png">
          <span>57</span>
      </div>
    </div>
  </div>

<div class="item">
  <img class="img-fluid" src="https://i.ibb.co/7R0Vzp3/account8.jpg">
  <div class="bg" <div="">
      <div class="likes">
          <img src="./images/heart_white.png">
          <span>100</span>
      </div>
      <div class="comments">
          <img src="./images/message.png">
          <span>57</span>
      </div>
    </div>
  </div>

<div class="item">
  <img class="img-fluid" src="https://i.ibb.co/gvrfhjL/account9.jpg">
  <div class="bg" <div="">
      <div class="likes">
          <img src="./images/heart_white.png">
          <span>100</span>
      </div>
      <div class="comments">
          <img src="./images/message.png">
          <span>57</span>
      </div>
    </div>
  </div>


</div><div class="item1">
<div class="item">
<img class="img-fluid" src="https://i.ibb.co/j8L7FPY/account10.jpg">
<div class="bg" <div="">
  <div class="likes">
      <img src="./images/heart_white.png">
      <span>100</span>
  </div>
  <div class="comments">
      <img src="./images/message.png">
      <span>57</span>
  </div>
</div>
</div>

</div><div class="items_4">
<div class="item">
  <img class="img-fluid" src="https://i.ibb.co/JcXRPht/account11.jpg">
  <div class="bg" <div="">
      <div class="likes">
          <img src="./images/heart_white.png">
          <span>100</span>
      </div>
      <div class="comments">
          <img src="./images/message.png">
          <span>57</span>
      </div>
    </div>
  </div>

<div class="item">
  <img class="img-fluid" src="https://i.ibb.co/6WvdZS9/account12.jpg">
  <div class="bg" <div="">
      <div class="likes">
          <img src="./images/heart_white.png">
          <span>100</span>
      </div>
      <div class="comments">
          <img src="./images/message.png">
          <span>57</span>
      </div>
    </div>
  </div>

<div class="item">
  <img class="img-fluid" src="https://i.ibb.co/pJ8thst/account13.jpg">
  <div class="bg" <div="">
      <div class="likes">
          <img src="./images/heart_white.png">
          <span>100</span>
      </div>
      <div class="comments">
          <img src="./images/message.png">
          <span>57</span>
      </div>
    </div>
  </div>

<div class="item">
  <img class="img-fluid" src="https://i.ibb.co/4M3W996/account14.jpg">
  <div class="bg" <div="">
      <div class="likes">
          <img src="./images/heart_white.png">
          <span>100</span>
      </div>
      <div class="comments">
          <img src="./images/message.png">
          <span>57</span>
      </div>
    </div>
  </div>


</div><div class="item1">
<div class="item">
<img class="img-fluid" src="https://i.ibb.co/3S1hjKR/account1.jpg">
<div class="bg" <div="">
  <div class="likes">
      <img src="./images/heart_white.png">
      <span>100</span>
  </div>
  <div class="comments">
      <img src="./images/message.png">
      <span>57</span>
  </div>
</div>
</div>

</div></div>

src/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block content %}
<script src="https://unpkg.com/htmx.org@2.0.1"></script>
{% include 'components/navbar/navbar.html' %}
{% include 'components/main/main.html' %}
{% include 'components/navbar/navbar2.html' %}
{% endblock %}

src/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagram</title>
    <link rel="shortcut icon" href="{% static 'assets/favicon.svg' %}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'sass/vender/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'sass/vender/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'owlcarousel/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'owlcarousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/emojionearea/3.4.2/emojionearea.min.css">
    <link rel="stylesheet" href="{% static 'sass/main.css' %}">
</head>
<body>
    <div class="post_page">
        <!--***** nav menu end ****** -->

        <div class="profile_container">
            <div class="profile_info">
                <div class="cart">
                        <div class="img">
                            <img src="{{request.user.profile.image.url}}" alt="">
                        </div>
                        <div class="info">
                            <p class="name">
                                {{request.user.get_full_name}}
                                <button class="edit_profile">
                                    Edit profile 
                                </button>
                            </p>
                            <div class="general_info">
                                <p><span>{{request.user.post_set.count}}</span> Posts</p>
                                <p><span>{{request.user.profile.followed_by.count}}</span> followers</p>
                                <p><span>{{request.user.profile.following.count}}</span> following</p>
                            </div>
                            <p class="nick_name">{{request.user.username}}</p>
                            <p class="desc">
                                {% if request.user.profile.bio %}
                                {{request.user.profile.bio}}
                                {% endif %}
                            </p>
                        </div>
                </div>
            </div>
            <div class="highlights">
                {% for i in request.user.profile.following.all %}
                <div class="highlight">
                    <div class="img">
                        <img src="{{i.image.url}}" alt="">
                    </div>
                    <p>{{i.user.get_full_name}}</p>
                </div>
                {% endfor %}
                <div class="highlight highlight_add">
                    <div class="img">
                        <img src="{% static 'images/plus.png' %}" alt="">
                    </div>
                    <p>New</p>
                </div>
            </div>
            <hr>
            <div class="posts_profile">
                <ul class="nav-pills w-100 d-flex justify-content-center" id="pills-tab" role="tablist">
                    <li class="nav-item mx-2" role="presentation">
                        <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">
                            <img src="{% static 'images/feed.png' %}" alt="posts">
                            POSTS({{request.user.post_set.count}})
                        </button>
                    </li>
                    <li class="nav-item mx-2" role="presentation">
                      <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">
                        <img src="{% static 'images/save-instagram.png' %}" alt="saved posts">
                        SAVED({{request.user.bookmark.count}})
                      </button>
                    </li>
                    <li class="nav-item mx-2" role="presentation">
                      <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">
                        <img src="{% static 'images/tagged.png' %}" alt="tagged posts">
                        TAGGED
                      </button>
                    </li>
                  </ul>
                  <div class="tab-content" id="pills-tabContent">
                    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
                        <div id="posts_sec" class="post">
                            {% for i in request.user.post_set.all %}
                            <div class="item">
                                <img class="img-fluid item_img" src="{{i.image.url}}" alt="">
                            </div>
                            {% empty %}
                            
                            {% endfor %}
                        </div>
                    </div>
                    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0">
                        <div id="saved_sec" class="post">
                            {% for j in request.user.bookmark.all %}
                            <div class="item">
                                <img class="img-fluid item_img" src="{{j.image.url}}" alt="">
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab" tabindex="0">
                        <div id="tagged" class="post">
                            <div class="item">
                                <img class="img-fluid item_img" src="https://i.ibb.co/Zhc5hHp/account4.jpg" alt="">
                            </div>
                            <div class="item">
                                <img class="img-fluid item_img" src="https://i.ibb.co/SPTNbJL/account5.jpg" alt="">
                            </div>
                        </div>
                    </div>
                    
                  </div>
            </div>
        </div>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>    
    <script src="{% static 'owlcarousel/jquery.min.js' %}"></script>
    <script src="{% static 'owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/carousel.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/emojionearea/3.4.2/emojionearea.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

src/templates/profiles.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagram</title>
    <link rel="shortcut icon" href="{% static 'assets/favicon.svg' %}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'sass/vender/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'sass/vender/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'owlcarousel/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'owlcarousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/emojionearea/3.4.2/emojionearea.min.css">
    <link rel="stylesheet" href="{% static 'sass/main.css' %}">
</head>
<body>
    <div class="post_page">
        <!--***** nav menu end ****** -->

        <div class="profile_container">
            <div class="profile_info">
                <div class="cart">
                        <div class="img">
                            <img src="{{user_profile.profile.image.url}}" alt="">
                        </div>
                        <div class="info">
                            <p class="name">
                                {{user_profile.get_full_name}}
                                {% if user_profile.profile in request.user.profile.following.all %}
                                <form action="{% url 'unfollow' user_profile.id %}" method="POST">
                                    {% csrf_token %}
                                    <button class="edit_profile">  
                                        <small>Unfollow</small>
                                    </button>
                                </form>
                                {% elif user_profile.profile in request.user.profile.followed_by.all %}
                                <form action="{% url 'follow' user_profile.id  %}" method="POST">{% csrf_token %}
                                <button type="submit" class="edit_profile">  
                                    Follow Back
                                </button> </form>
                                {% else %}
                                <form action="{% url 'follow' user_profile.id  %}" method="POST">{% csrf_token %}
                                    <button type="submit" class="edit_profile">  
                                        Follow
                                    </button>
                                </form>
                                {% endif %}
                            </p>
                            <div class="general_info">
                                <p><span>{{user_profile.post_set.count}}</span> Posts</p>
                                <p><span>{{user_profile.profile.followed_by.count}}</span> followers</p>
                                <p><span>{{user_profile.profile.following.count}}</span> following</p>
                            </div>
                            <p class="nick_name">{{user_profile.username}}</p>
                            <p class="desc">
                                {% if user_profile.profile.bio %}
                                {{user_profile.profile.bio}}
                                {% endif %}
                            </p>
                        </div>
                </div>
            </div>
            <div class="highlights">
                {% for i in user_profile.profile.following.all %}
                <div class="highlight">
                    <div class="img">
                        <img src="{{i.image.url}}" alt="">
                    </div>
                    <p>{{i.user.get_full_name}}</p>
                </div>
                {% endfor %}
                <div class="highlight highlight_add">
                    <div class="img">
                        <img src="{% static 'images/plus.png' %}" alt="">
                    </div>
                    <p>New</p>
                </div>
            </div>
            <hr>
            <div class="posts_profile">
                <ul class="nav-pills w-100 d-flex justify-content-center" id="pills-tab" role="tablist">
                    <li class="nav-item mx-2" role="presentation">
                        <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">
                            <img src="{% static 'images/feed.png' %}" alt="posts">
                            POSTS({{user_profile.post_set.count}})
                        </button>
                    </li>
                    {% if user_profile == request.user %}
                    <li class="nav-item mx-2" role="presentation">
                      <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">
                        <img src="{% static 'images/save-instagram.png' %}" alt="saved posts">
                        SAVED({{user_profile.bookmark.count}})
                      </button>
                    </li>
                    {% endif %}
                    <li class="nav-item mx-2" role="presentation">
                      <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">
                        <img src="{% static 'images/tagged.png' %}" alt="tagged posts">
                        TAGGED
                      </button>
                    </li>
                  </ul>
                  <div class="tab-content" id="pills-tabContent">
                    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
                        <div id="posts_sec" class="post">
                            {% for i in user_profile.post_set.all %}
                            <div class="item">
                                <img class="img-fluid item_img" src="{{i.image.url}}" alt="">
                            </div>
                            {% empty %}
                            
                            {% endfor %}
                        </div>
                    </div>
                    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0">
                        <div id="saved_sec" class="post">
                            {% if user_profile == request.user %}
                            {% for j in user_profile.bookmark.all %}
                            <div class="item">
                                <img class="img-fluid item_img" src="{{j.image.url}}" alt="">
                            </div>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab" tabindex="0">
                        <div id="tagged" class="post">
                            <div class="item">
                                <img class="img-fluid item_img" src="https://i.ibb.co/Zhc5hHp/account4.jpg" alt="">
                            </div>
                            <div class="item">
                                <img class="img-fluid item_img" src="https://i.ibb.co/SPTNbJL/account5.jpg" alt="">
                            </div>
                        </div>
                    </div>
                    
                  </div>
            </div>
        </div>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>    
    <script src="{% static 'owlcarousel/jquery.min.js' %}"></script>
    <script src="{% static 'owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/carousel.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/emojionearea/3.4.2/emojionearea.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>